=== likuisuper/core-java/src/tech/aistar/day18/homework/student.dtd
<?xml version="1.0" encoding="UTF-8"?>

        <!ELEMENT students (student+)>
        <!ELEMENT student (name,no,birthday,adress)>
        <!ATTLIST student
                id CDATA #REQUIRED>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT no (#PCDATA)>
        <!ELEMENT birthday (#PCDATA)>
        <!ELEMENT adress (province,city)>

        <!ELEMENT province (#PCDATA)>
        <!ELEMENT city (#PCDATA)>

=== likuisuper/core-java/src/tech/aistar/day18/homework/student.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--<!DOCTYPE students SYSTEM 'student.dtd'>-->

<students>


    <student id="101">

        <name>lk</name>

        <no>60</no>

        <birthday>1998-10-19</birthday>


        <adress>

            <province>江苏</province>

            <city>苏州</city>

        </adress>

    </student>


    <student id="102">

        <name>sbczw</name>

        <no>61</no>

        <birthday>1998-09-12</birthday>


        <adress>

            <province>M78</province>

            <city>狮子座</city>

        </adress>

    </student>

</students>
